#!/bin/bash
clear
echo "Select which filter you want to apply."
echo "1. Wood"
echo "2. Brushed metal."
echo "3. Cutout."
echo "4. Glass."
echo "5. Disable filter."
echo "6. Back to main menu."

read input

if [ "$input" = "1" ]; then
	filter=`bash filters/wood`
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../real_icons/*/*.svg
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../logos/*
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../alt_folders/*/*/*.svg
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
	killall gnome-panel
	killall fbpanel
	nohup fbpanel &
	sleep 1
	clear
	echo "Finnished, press any key to return to the filter menu."
	read -n 1
fi
if [ "$input" = "2" ]; then
	filter=`bash filters/brushed_metal`
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../real_icons/*/*.svg
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../logos/*
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../alt_folders/*/*/*.svg
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
	killall gnome-panel
	killall fbpanel
	nohup fbpanel &
	sleep 1
	clear
	echo "Finnished, press any key to return to the filter menu."
	read -n 1
fi
if [ "$input" = "3" ]; then
	filter=`bash filters/cutout`
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../real_icons/*/*.svg
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../logos/*
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../alt_folders/*/*/*.svg
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
	killall gnome-panel
	killall fbpanel
	nohup fbpanel &
	sleep 1
	clear
	echo "Finnished, press any key to return to the filter menu."
	read -n 1
fi
if [ "$input" = "4" ]; then
	filter=`bash filters/glass`
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../real_icons/*/*.svg
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../logos/*
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"$filter"'+smg' ../alt_folders/*/*/*.svg
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
	killall gnome-panel
	killall fbpanel
	nohup fbpanel &
	sleep 1
	clear
	echo "Finnished, press any key to return to the filter menu."
	read -n 1
fi
if [ "$input" = "5" ]; then
	perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"<filter>\n    </filter>"'+smg' ../real_icons/*/*.svg
perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"<filter>\n    </filter>"'+smg' ../logos/*
perl -i -pe 'BEGIN{undef $/;} s+<filter.*</filter>+'"<filter>\n    </filter>"'+smg' ../alt_folders/*/*/*.svg
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
	gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
	killall gnome-panel
	killall fbpanel
	nohup fbpanel &
	sleep 1
	clear
	echo "Finnished, press any key to return to the filter menu."
	read -n 1
fi
if [ "$input" = "6" ]; then
	bash script_menu
	exit
fi
clear
bash script_filter_all
exit
