#!/bin/bash
clear
echo "Main menu"
echo "Enter the number of the action you want to preform."
echo "1. Set color."
echo "2. Set gradient."
echo "3. Switch icons."
echo "4. Apply filer."
echo "5. Advanced."
echo "6. Exit"

read input

if [ "$input" = "1" ]; then
	clear
	echo "Color menu"
	echo "Enter the number of the action you want to preform."
	echo "1. Set colors on all icons."
	echo "2. Set colors on actions."
	echo "3. Set colors on emblems."
	echo "4. Set colors on all icons except actions and emblems."
	echo "5. Back to main menu."
	read input2
	if [ "$input2" = "1" ]; then
		bash script_color_all
		exit
	fi
	if [ "$input2" = "2" ]; then
		bash script_color_actions
		exit
	fi
	if [ "$input2" = "3" ]; then
		bash script_color_emblem
		exit
	fi
	if [ "$input2" = "4" ]; then
		bash script_color_except
		exit
	fi
	if [ "$input2" = "5" ]; then
		clear
		bash script_menu
		exit
	fi
fi
if [ "$input" = "2" ]; then
	clear
	echo "Gradient menu"
	echo "Enter the number of the action you want to preform."
	echo "1. Set gradient on all icons."
	echo "2. Set gradient on actions."
	echo "3. Set gradient on emblems."
	echo "4. Set gradient on all icons except actions and emblems."
	echo "5. Back to main menu."
	read input2
	if [ "$input2" = "1" ]; then
		bash script_gradient_all
		exit
	fi
	if [ "$input2" = "2" ]; then
		bash script_gradient_actions
		exit
	fi
	if [ "$input2" = "3" ]; then
		bash script_gradient_emblem
		exit
	fi
	if [ "$input2" = "4" ]; then
		bash script_gradient_except
		exit
	fi
	if [ "$input2" = "5" ]; then
		clear
		bash script_menu
		exit
	fi
	exit
fi
if [ "$input" = "3" ]; then
	clear
		bash script_alt_icon
		exit
fi
if [ "$input" = "4" ]; then
	clear
	echo "Filter menu"
	echo "Enter the number of the action you want to preform."
	echo "1. Apply filter on all icons."
	echo "2. Apply filter on actions."
	echo "3. Apply filter on emblems."
	echo "4. Apply filter on all icons except actions and emblems."
	echo "5. Back to main menu."
	read input2
	if [ "$input2" = "1" ]; then
		bash script_filter_all
		exit
	fi
	if [ "$input2" = "2" ]; then
		bash script_filter_actions
		exit
	fi
	if [ "$input2" = "3" ]; then
		bash script_filter_emblem
		exit
	fi
	if [ "$input2" = "4" ]; then
		bash script_filter_except
		exit
	fi
	if [ "$input2" = "5" ]; then
		clear
		bash script_menu
		exit
	fi
	exit
fi
while [[ "$input" = "5" ]]
do
	clear
	echo "Advanced menu"
	echo "Enter the number of the action you want to preform."
	echo "1. Copy icon-theme with settings to root user.(Requiers password)"
	echo "2. Create menu icon and terminal command to run this script.(Requiers password)"
	echo "3. Remove the files created by option 1 and 2.(Requiers password)"
	echo "4. Fix taskbar icons on apps that don't follow the icon theme.(Requiers fbpanel)"
	echo "5. Back to main menu."
	read input2
	if [ "$input2" = "1" ]; then
		sudo cp -r ../../ /usr/share/icons/ACYL_Icon_Theme_0.7.1/
		clear
		bash script_menu
		exit
	fi
	if [ "$input2" = "2" ]; then
		sudo cp ../other/acyl /usr/bin/acyl
		sudo cp ../other/acyl.desktop /usr/share/applications/acyl.desktop
		clear
		echo "Now you sould have an icon in your gnome-menu for running this script."
		echo "It should be located under setting."
		echo "You can also run it by typing (acyl) in your termnal"
		echo "Press any key to return to the main menu."
		read -n 1
		clear
		bash script_menu
		exit
	fi
	if [ "$input2" = "3" ]; then
		sudo rm /usr/bin/acyl
		sudo rm /usr/share/applications/acyl.desktop
		sudo rm ~/.config/autostart/fbpanel.desktop
		sudo rm ~/.fbpanel/default
		sudo rmdir /usr/share/icons/ACYL_Icon_Theme_0.7.1
		clear
		bash script_menu
		exit
	fi
	if [ "$input2" = "4" ]; then
		bash script_fbpanel
		clear
		bash script_menu
		exit
	fi
	if [ "$input2" = "5" ]; then
		clear
		bash script_menu
		exit
	fi
done
if [ "$input" = "6" ]; then
	exit
fi
clear
bash script_menu
exit
