-- local rectLauncher = {}
-- local rectLauncherWdg = {}
--
-- function setupRectLauncher(column, arg) 
--   
--   if rectLauncherWdg[column] == nil then
--     rectLauncherWdg[column] = { layout = awful.widget.layout.horizontal.leftright }
--   end
--   
--   newLauncher = widget({ type = "imagebox"})
--   newLauncher.image = image(arg[1])
--   
--   table.insert(rectLauncherWdg[column], newLauncher)
--   
-- end
-- 
-- function loadRectLauncher(s2)
--   for i, column in ipairs(rectLauncherWdg) do
--     local aWibox = awful.wibox({ position = "free", screen = s})
--     local relX = -25 --screen[1].geometry.x -500
--     for j =1, screen.count() - s2 +2 do
--       relX = relX + screen[j].geometry.width
--     end
--     relX = relX - 250
--     local relY = screen[1].geometry.height - 25 - 400
--     aWibox:geometry({ width = 250, height = 400, x =relX - (260 *(i-1)), y = relY})
--     aWibox.bg = "#ff000000"
--     aWibox.widgets = column
--   end
-- end