return {
  showTitleBar = false,
  noNotifyPopup = true,
  themeName = "darkBlue",
  desktopIcon = true,
  iconPath = "/home/lepagee/.config/awesome/theme/darkBlue//Icon/",
  scr = {
  media = 4,
  irc = 5,
  pri = 1,
  music = 3,
  sec = 2,

},
  advTermTB = true,
  themePath = "/home/lepagee/.config/awesome/theme/darkBlue/",
  scriptPath = "/home/lepagee/.config/awesome/Scripts/",
  listPrefix = {
  [1] = "①",
  [2] = "②",
  [3] = "③",
  [4] = "④",
  [5] = "⑤",
  [6] = "⑥",
  [7] = "⑦",
  [8] = "⑧",
  [9] = "⑨",
  [10] = "⑩",
  [11] = "⑪",
  [12] = "⑫",
  [13] = "⑬",
  [14] = "⑭",
  [15] = "⑮",
  [16] = "⑯",
  [17] = "⑰",
  [18] = "⑱",
  [19] = "⑲",
  [20] = "⑳",

},
  useListPrefix = true,
  deviceOnDesk = true,

} 
