require("customMenu.layoutmenu")
require("customMenu.application")
require("customMenu.places")
require("customMenu.tagOption")
require("customMenu.clientMenu")
require("customMenu.altTab")
require("customMenu.aeroTag")
require("customMenu.launcher")
require("customMenu.logout")

module("customMenu")