#! usr/bin/bash
echo '<filter
     id="filter1111"
     height="1.7"
     y="-0.30000001"
     width="1.2"
     x="-0.1"
     color-interpolation-filters="sRGB">
    <feGaussianBlur
       id="feGaussianBlur2819"
       result="result8"
       stdDeviation="4" />
    <feTurbulence
       id="feTurbulence2821"
       baseFrequency="0.015000000000000003 0.40000000000000002"
       numOctaves="10"
       type="fractalNoise"
       result="result7"
       seed="22" />
    <feComposite
       id="feComposite2823"
       in2="result8"
       operator="in"
       in="SourceGraphic"
       result="result6"
       k1="0.25742574257425765" />
    <feDisplacementMap
       id="feDisplacementMap2825"
       in2="result6"
       result="result4"
       scale="4"
       yChannelSelector="A"
       xChannelSelector="A"
       in="result7" />
    <feFlood
       id="feFlood2827"
       flood-color="rgb(230,211,138)"
       flood-opacity="1"
       in="result4"
       result="result9" />
    <feComposite
       id="feComposite2829"
       in2="result4"
       operator="out"
       result="result2" />
    <feComposite
       id="feComposite2831"
       operator="atop"
       in="result2"
       result="result9"
       in2="SourceGraphic" />
    <feComposite
       id="feComposite2839"
       in2="result9"
       operator="in"
       result="result2"
       in="result1" />
    <feComposite
       id="feComposite2841"
       in2="result2"
       k3="2.7755575615628914e-17"
       k2="0.89999999999999991"
       operator="arithmetic"
       result="result4"
       in="result9"
       k1="0.30000000000000004"
       k4="0" />
  </filter>'
