require( "widgets.desktopMonitor"       )
require( "widgets.dock"                 )
require( "widgets.devices"              )
require( "widgets.keyboardSwitcher"     )
require( "widgets.spacer"               )
-- require( "widgets.taglist"              )
-- require( "widgets.tasklist"             )
-- require( "widgets.tablist"              )
-- require( "widgets.tablist_old"          )
-- require( "widgets.tabbar"               )
-- require( "widgets.titlebar"             )
require( "widgets.menu"                 )
require( "widgets.menu4"                )
require( "widgets.desktopIcon"          )
require( "widgets.checkbox"             )
require( "widgets.layout.desktopLayout" )
require( "widgets.radialSelect"         )
require( "widgets.menuDeco"             )
-- require( "widgets.overlay"              )
require( "widgets.tooltip"              )
require( "widgets.tooltip2"             )

module("widgets")
