require("widgets.desktopMonitor")
require("widgets.dock")
require("widgets.devices")
require("widgets.keyboardSwitcher")
require("widgets.spacer")
require("widgets.taglist")
require("widgets.tasklist")
require("widgets.tablist")
require("widgets.tabbar")
require("widgets.titlebar")
require("widgets.menu")

module("widgets")