#!/bin/bash

echo "What kind of gradient do you want?"
echo "1. Linear"
echo "2. Radial"
echo "3. Back to main menu."
read gradsort

if [[ "$gradsort" = 3 ]]
then
bash script_menu
exit
fi

if [[ "$gradsort" != [1,2,3.4] ]]
then
	clear
	echo "Invalid input."
	bash script_gradient_all
	exit
fi

echo "Press any key to select the first color."
read -n 1
colorvar=`python script_pycolor`
red=`echo $colorvar | cut -d \  -f 1`
green=`echo $colorvar | cut -d \  -f 2`
blue=`echo $colorvar | cut -d \  -f 3`
alpha=`echo $colorvar | cut -d \  -f 4`

if [[ "$colorvar" = "" ]]
then
	bash script_menu
	exit
fi

echo "Done"

if [[ "$red" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	red="0"$red
fi

if [[ "$green" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	green="0"$green
fi

if [[ "$blue" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	blue="0"$blue
fi

color1=stop-color:#$red$green$blue
opacity1=stop-opacity:$alpha

echo "Press any key to select the second color."
read -n 1
colorvar=`python script_pycolor`
red=`echo $colorvar | cut -d \  -f 1`
green=`echo $colorvar | cut -d \  -f 2`
blue=`echo $colorvar | cut -d \  -f 3`
alpha=`echo $colorvar | cut -d \  -f 4`

if [[ "$colorvar" = "" ]]
then
	bash script_menu
	exit
fi

echo "Done"

if [[ "$red" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	red="0"$red
fi

if [[ "$green" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	green="0"$green
fi

if [[ "$blue" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	blue="0"$blue
fi

color2=stop-color:#$red$green$blue
opacity2=stop-opacity:$alpha

basegrad='id="linearGradient4321">\n    <stop\n       style="'$color1';'$opacity1';"\n       offset="0"\n       id="stop1" />\n    <stop\n       style="'$color2';'$opacity2';"\n       offset="1"\n       id="stop2" />\n  </linearGradient>'


cualpha=`bash current_state/current_opacity`
cualphaem=`bash current_state/current_opacity_emblems`
cualphaac=`bash current_state/current_opacity_actions`
cucolor=`bash current_state/current_color`
cucolorac=`bash current_state/current_color_actions`
cucolorem=`bash current_state/current_color_emblems`

if [[ "$gradsort" = 1 ]]
then

	echo "Select gradient direction."
	echo "1.Horizontal"
	echo "2.Vertical"
	echo "3.Diagonally"
	read linedirection
	if [[ "$linedirection" = 1 ]]
	then
		linegrad='  <linearGradient\n     inkscape:collect="always"\n     xlink:href="#linearGradient4321"\n     id="linearGradient1234"\n     x1="0%"\n     y1="50%"\n     x2="100%"\n     y2="50%" />'
	fi
	if [[ "$linedirection" = 2 ]]
	then
		linegrad='  <linearGradient\n     inkscape:collect="always"\n     xlink:href="#linearGradient4321"\n     id="linearGradient1234"\n     x1="50%"\n     y1="0%"\n     x2="50%"\n     y2="100%" />'
	fi
	if [[ "$linedirection" = 3 ]]
	then
		linegrad='  <linearGradient\n     inkscape:collect="always"\n     xlink:href="#linearGradient4321"\n     id="linearGradient1234"\n     x1="0%"\n     y1="0%"\n     x2="100%"\n     y2="100%" />'
	fi
	if [[ "$linedirection" != [1,2,3] ]]
	then
		bash scrip_menu
		exit
	fi
	wholegrad=$basegrad'\n'$linegrad
fi

if [[ "$gradsort" = 2 ]]
then
	r=$(zenity --scale --text "Enter the radius of the gradient. (50% default)" --min-value=1 --max-value=100 --value=50 --step 1)'%'
	while [[ $r = "%" ]]
	do
		clear
		bash script_menu
		exit
	done
	cx=$(zenity --scale --text "Enter the x-coordinate for the center point of the gradient. A number or percentage. (50% default)" --min-value=-200 --max-value=200 --value=50 --step 1)'%'
	while [[ $cx = "%" ]]
	do
		clear
		bash script_menu
		exit
	done
	cy=$(zenity --scale --text "Enter the y-coordinate for the center point of the gradient. A number or percentage. (50% default)" --min-value=-200 --max-value=200 --value=50 --step 1)'%'
	while [[ $cx = "%" ]]
	do
		clear
		bash script_menu
		exit
	done
	fx=$(zenity --scale --text "Enter the x-coordinate for the focus point of the gradient. A number or percentage. (50% default)" --min-value=-200 --max-value=200 --value=50 --step 1)'%'
	while [[ $cx = "%" ]]
	do
		clear
		bash script_menu
		exit
	done
	fy=$(zenity --scale --text "Enter the y-coordinate for the focus point of the gradient. A number or percentage. (50% default)" --min-value=-200 --max-value=200 --value=50 --step 1)'%'
	while [[ $cx = "%" ]]
	do
		clear
		bash script_menu
		exit
	done

	radigrad='    <radialGradient\n       inkscape:collect="always"\n       xlink:href="#linearGradient4321"\n       id="radialGradient1234"\n       cx="'$cx'"\n       cy="'$cy'"\n       fx="'$fx'"\n       fy="'$fy'"\n       r="'$r'"\n/>'
	wholegrad=$basegrad'\n'$radigrad
fi

echo "Pelease wait for your change to take affekt."

	#Main alpha override
sed -i 's+'"$cualphaac"'+fill-opacity:1.0+g' ../real_icons/actions/*.svg

sed -i 's+'"$cualphaac"'+fill-opacity:1.0+g' ./current_state/current_opacity_actions


	#Curent gradeinet set
cucstop1=`bash current_state/current_stop_color_1`
cucstop2=`bash current_state/current_stop_color_2`
cuostop1=`bash current_state/current_stop_opacity_1`
cuostop2=`bash current_state/current_stop_opacity_2`

sed -i 's+'"$cucstop1"'+'"$color1"'+g' ./current_state/current_stop_color_1
sed -i 's+'"$cucstop2"'+'"$color2"'+g' ./current_state/current_stop_color_2
sed -i 's+'"$cuostop1"'+'"$opacity1"'+g' ./current_state/current_stop_opacity_1
sed -i 's+'"$cuostop2"'+'"$opacity2"'+g' ./current_state/current_stop_opacity_2

	#Gradient set


perl -i -pe 'BEGIN{undef $/;} s+id="linearGradient4321">.*<defs+'"$wholegrad"'\n<defs+smg' ../real_icons/actions/*.svg

if [[ "$gradsort" = 1 ]]
then
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/animations/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/apps/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/categories/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/devices/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/mimetypes/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/places/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/status/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../real_icons/stock/*.svg
	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ../logos/*

	sed -i 's+'"$cucolorac"'+fill:url(#linearGradient1234)+g' ../real_icons/actions/*.svg
	sed -i 's+'"$cucolorem"'+fill:url(#linearGradient1234)+g' ../real_icons/emblems/*.svg

	sed -i 's+'"$cucolor"'+fill:url(#linearGradient1234)+g' ./current_state/current_color
	sed -i 's+'"$cucolorac"'+fill:url(#linearGradient1234)+g' ./current_state/current_color_actions
	sed -i 's+'"$cucolorem"'+fill:url(#linearGradient1234)+g' ./current_state/current_color_emblems
fi

if [[ "$gradsort" = 2 ]]
then
	sed -i 's+'"$cucolorac"'+fill:url(#radialGradient1234)+g' ../real_icons/actions/*.svg

	sed -i 's+'"$cucolor"'+fill:url(#radialGradient1234)+g' ./current_state/current_color
	sed -i 's+'"$cucolorac"'+fill:url(#radialGradient1234)+g' ./current_state/current_color_actions
fi
gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
killall gnome-panel
killall fbpanel
nohup fbpanel &
sleep 1
clear
echo "Finnished, press any key to return to the main menu."
read -n 1
clear
bash script_menu
