#!/bin/bash
clear
until test -e /usr/bin/fbpanel;
do
	clear
	echo "This action requiers fbpanel to be installed."
	echo "If you can't find it in your repository you can find the source code"
	echo "at their homepage here: http://fbpanel.sourceforge.net/."
	echo "Press any key to return to the advanced menu."
	read -n 1
	bash script_advanced
	exit
done

until test -e ~/.config/autostart/fbpanel.desktop;
do
	echo "Do you want fbpanel to auotostart at startup?"
	echo "This is requierd for this funktion to work properly"
	echo "Y/N?"

	read ans1

	if [[ "$ans1" = ["[y,Y,yes,Yes]"] ]];
	then
		cp ../other/fbpanel.desktop ~/.config/autostart/fbpanel.desktop
	else
		bash script_advanced
		exit
	fi
	clear
done

until test -e ~/.fbpanel/default;
do
	echo "Do you want to create fbpanels config file?"
	echo "This is requierd for this funktion to work"
	echo "y/n?"

	read ans2

	if [[ "$ans2" = ["[y,Y,yes,Yes]"] ]];
	then
		if [ test -e ~/.fbpanel ]
		then
			cp ../other/default ~/.fbpanel/default
		else
			mkdir ~/.fbpanel
			cp ../other/default ~/.fbpanel/default
		fi

	else
		bash script_advanced
		exit
	fi
	clear
done

clear
echo "Do you want to set icons for a special application?"
echo "Make sure you have the application in question open and visible."
echo "Y/N?"

read ans3

if [[ "$ans3" = ["[y,Y,yes,Yes]"] ]];
then
	echo "Press the window of the application you want to set an icon for."
	wm_class=`xprop | grep WM_CLASS | cut -d , -f 2 | cut -d \" -f 2`
	clear

	echo "The class of the window you selected is "$wm_class"."
	echo "Now select which icon you want the application to use."
	echo "Press any key to continue."
	read -n 1

	cd ../apps
	iconpath=`zenity --file-selection`
	cd ../scripts

	while [[ $iconpath = "" ]]
	do
		clear
		killall fbpanel
		fbpanel &
		bash script_advanced
		exit
	done

	perl -pi -e "s*config {*config {\napplication {\n            Image = $iconpath\n            ClassName = $wm_class\n        }*" ~/.fbpanel/default
fi

killall fbpanel
nohup fbpanel &
clear
bash script_advanced
exit
