#!/bin/bash
echo "Enter the number of the logo you want to use."
echo "1. Arch."
echo "2. Debian."
echo "3. Fedora."
echo "4. Gnome"
echo "5. Ubuntu."
echo "6. Custom."
echo "7. Set custom logo."
echo "8. Go back."

read input

if [ "$input" = "1" ]; then
               cp -r ../logos/arch ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/arch ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "2" ]; then
               cp -r ../logos/debian ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/debian ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "3" ]; then
               cp -r ../logos/fedora ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/fedora ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "4" ]; then
               cp -r ../logos/gnome ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/gnome ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "5" ]; then
               cp -r ../logos/ubuntu ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/ubuntu ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "6" ]; then
               cp -r ../logos/custom ../real_icons/apps/checkbox-gtk.svg
               cp -r ../logos/custom ../real_icons/places/distributor-logo.svg
            fi
if [ "$input" = "7" ]; then
               clear

               cucolor=`bash current_state/current_color`
               cualpha=`bash current_state/current_opacity`

               cstop1=`bash current_state/current_stop_color_1`
               cstop2=`bash current_state/current_stop_color_2`
               ostop1=`bash current_state/current_stop_opacity_1`
               ostop2=`bash current_state/current_stop_opacity_2`

               gradient='    <linearGradient\n     id="linearGradient4321">\n    <stop\n       style="'$cstop1';'$ostop1';"\n       offset="0"\n       id="stop1" />\n    <stop\n       style="'$cstop2';'$ostop2';"\n       offset="1"\n       id="stop2" />\n  </linearGradient>\n  <linearGradient\n     inkscape:collect="always"\n     xlink:href="#linearGradient4321"\n     id="linearGradient1234"\n     x1="0%"\n     y1="50%"\n     x2="100%"\n     y2="50%" />'

               echo "Select which icon to set as your custom logo."
               echo "Preferabbly it should be a .svg file."

               cd ../apps/
               logo=`zenity --title="Select which icon to set as your custom logo" --file-selection`

		while [[ $logo = "" ]]
		do
			cd ../scripts/
			clear
			bash script_logos
			exit
		done
		
               cd ../scripts/

               cp -r "$logo" ../logos/custom

               clear
               echo "To use your new logo choose option 6. in the logo menu."
	       echo "Press any key to return to the logo menu."
               read -n 1
               bash script_logos
               exit
fi

if [ "$input" = "8" ]; then
               bash script_alt_icon
               exit
            fi

gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
killall gnome-panel

clear
bash script_logos
