#! usr/bin/bash

colorvar=`python script_pycolor`
if [[ "$colorvar" = "" ]]
then
	bash script_menu
	exit
fi

echo "Pelease wait for your change to take affekt."

red=`echo $colorvar | cut -d \  -f 1`
green=`echo $colorvar | cut -d \  -f 2`
blue=`echo $colorvar | cut -d \  -f 3`
alpha=`echo $colorvar | cut -d \  -f 4`

if [[ "$red" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	red="0"$red
fi

if [[ "$green" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	green="0"$green
fi

if [[ "$blue" = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,A,B,C,D,E,F] ]]
then
	blue="0"$blue
fi

input=#$red$green$blue
cualpha=`bash current_state/current_opacity`
cualphaem=`bash current_state/current_opacity_emblems`
cualphaac=`bash current_state/current_opacity_actions`
cucolor=`bash current_state/current_color`
cucolorac=`bash current_state/current_color_actions`
cucolorem=`bash current_state/current_color_emblems`

basegrad='id="linearGradient4321">\n    <stop\n       style="stop-color:'$input';stop-opacity:'$alpha';"\n       offset="0"\n       id="stop1" />\n    <stop\n       style="stop-color:'$input';stop-opacity:'$alpha';"\n       offset="1"\n       id="stop2" />\n  </linearGradient>'

perl -i -pe 'BEGIN{undef $/;} s+id="linearGradient4321">.*  </linearGradient>+'"$basegrad"'+smg' ../real_icons/actions/*svg

gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
killall gnome-panel
killall fbpanel
nohup fbpanel &
sleep 1
clear
echo "Finnished, press any key to return to the main menu."
read -n 1
clear
bash script_menu
