#!/bin/bash
echo "Enter the number of the logo you want to use."
echo "1. Acyl folder 1 (default)."
echo "2. Acyl folder 2."
echo "3. Acyl folder 3."
echo "4. Acyl folder 4"
echo "5. Acyl folder 5."
echo "6. Go back."

read input

if [ "$input" = "1" ]; then
               cp -R ../alt_folders/acyl_1/* ../real_icons
            fi
if [ "$input" = "2" ]; then
               cp -R ../alt_folders/acyl_2/* ../real_icons
            fi
if [ "$input" = "3" ]; then
               cp -R ../alt_folders/acyl_3/* ../real_icons
            fi
if [ "$input" = "4" ]; then
               cp -R ../alt_folders/acyl_4/* ../real_icons
            fi
if [ "$input" = "5" ]; then
               cp -R ../alt_folders/acyl_5/* ../real_icons
            fi
if [ "$input" = "6" ]; then
               bash script_alt_icon
               exit
            fi

gconftool-2 --type string --set /desktop/gnome/interface/icon_theme default
gconftool-2 --type string --set /desktop/gnome/interface/icon_theme ACYL_Icon_Theme_0.8
killall gnome-panel

clear
bash script_folder
