#! usr/bin/bash
echo '<filter
     label="brushed metal button"
     id="filter1111"
     color-interpolation-filters="sRGB">
    <feDiffuseLighting
       diffuseConstant="0.44843048"
       result="result1"
       surfaceScale="16.20000076"
       id="feDiffuseLighting3017">
      <fePointLight
         z="10000"
         y="-20000"
         x="0"
         id="fePointLight3019" />
    </feDiffuseLighting>
    <feSpecularLighting
       kernelUnitLength="0.01"
       lighting-color="#ffffff"
       in="result1"
       result="result2"
       specularConstant="0"
       specularExponent="123.09742737"
       surfaceScale="-19.1972084"
       id="feSpecularLighting3021">
      <fePointLight
         z="99999"
         y="0"
         x="0"
         id="fePointLight3023" />
    </feSpecularLighting>
    <feComposite
       in="result1"
       in2="SourceAlpha"
       operator="in"
       result="result6"
       id="feComposite3025" />
    <feComposite
       result="result7"
       operator="atop"
       id="feComposite3027"
       in="result2"
       in2="result6" />
    <feMorphology
       id="feMorphology3029"
       radius="0.5"
       operator="erode"
       in="SourceGraphic"
       result="result6" />
    <feComposite
       id="feComposite3031"
       operator="arithmetic"
       k1="0.93"
       k2="0.54373522"
       k3="0.6855792"
       k4="-0.07"
       result="result5"
       stdDeviation="0.10000000000000001"
       radius="1.5"
       in="result7"
       in2="SourceGraphic" />
    <feTurbulence
       result="result6"
       numOctaves="3"
       baseFrequency="0.0050000000000000001 0.250"
       id="feTurbulence3033"
       seed="0" />
    <feColorMatrix
       result="result6"
       type="matrix"
       id="feColorMatrix3035"
       values="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0.6 " />
    <feComposite
       result="result6"
       in="result6"
       operator="in"
       in2="result5"
       id="feComposite3037"
       k1="1.8493150684931514"
       k2="0.75342465753424648"
       k3="2.4315068493150687"
       k4="0.20547945205479579" />
    <feMerge
       id="feMerge3039"
       result="result8">
      <feMergeNode
         in="result5"
         id="feMergeNode3041"
         collect="always" />
      <feMergeNode
         inkscape:collect="always"
         id="feMergeNode2842"
         in="result6" />
    </feMerge>
  </filter>'
