require("utils.tools")
require("utils.clientSwitcher")
require("utils.keyFunctions")
require("utils.mouseManager")
require("utils.urxvtIntegration")
require("utils.persistent")
require("utils.macro")
require("utils.theme")

module("utils")