#! usr/bin/bash
echo '<filter
     id="filter1111"
     inkscape:label="Cutout"
     inkscape:menu="Shadows and Glows"
     inkscape:menu-tooltip="Drop shadow under the cut-out of the shape"
     color-interpolation-filters="sRGB"
     x="-0.1"
     y="-0.1"
     width="1.2"
     height="1.2">
    <feGaussianBlur
       id="feGaussianBlur2834"
       stdDeviation="3.6"
       in="SourceAlpha"
       result="result94" />
    <feOffset
       id="feOffset2836"
       dy="3"
       dx="3"
       result="result91" />
    <feComposite
       id="feComposite2838"
       operator="out"
       result="result93"
       in2="result91"
       in="SourceGraphic" />
    <feMerge
       id="feMerge2854">
      <feMergeNode
         inkscape:collect="always"
         id="feMergeNode2856"
         in="result93" />
    </feMerge>
  </filter>'
